namespace SuperOverlay.LayoutEditor;

public static class LayoutEditorRawFieldCatalog
{
    private static readonly IReadOnlyList<string> TelemetryFields =
    [
        "Speed",
        "Gear",
        "RPM",
        "ShiftIndicatorPct",
        "Throttle",
        "Brake",
        "Clutch",
        "SteeringWheelAngle",
        "SteeringWheelPctTorque",
        "Lap",
        "LapCompleted",
        "LapCurrentLapTime",
        "LapLastLapTime",
        "LapBestLapTime",
        "LapDistPct",
        "LapDeltaToBestLap",
        "LapDeltaToSessionBestLap",
        "SessionLapsRemain",
        "SessionTimeRemain",
        "SessionFlags",
        "PlayerCarPosition",
        "PlayerCarClassPosition",
        "CarIdxPosition[0]",
        "CarIdxClassPosition[0]",
        "FuelLevel",
        "FuelLevelPct",
        "FuelUsePerHour",
        "OilTemp",
        "WaterTemp",
        "Voltage",
        "OnPitRoad",
        "PitSvFlags",
        "PitSvFuel",
        "SpeedLimiter",
        "IsOnTrack",
        "IsInGarage",
        "IsReplayPlaying",
        "Yaw",
        "Pitch",
        "Roll",
        "VelocityX",
        "VelocityY",
        "VelocityZ",
        "LatAccel",
        "LongAccel",
        "VertAccel"
    ];

    private static readonly IReadOnlyList<string> SessionInfoFields =
    [
        "WeekendInfo.TrackName",
        "WeekendInfo.TrackDisplayName",
        "WeekendInfo.TrackDisplayShortName",
        "WeekendInfo.TrackConfigName",
        "WeekendInfo.TrackType",
        "WeekendInfo.TrackDirection",
        "WeekendInfo.TrackWeatherType",
        "WeekendInfo.TrackSkies",
        "WeekendInfo.TrackAirTemp",
        "WeekendInfo.TrackSurfaceTemp",
        "WeekendInfo.TrackWindVel",
        "WeekendInfo.TrackWindDir",
        "WeekendInfo.SeriesID",
        "WeekendInfo.SeasonID",
        "WeekendInfo.SessionID",
        "WeekendInfo.SubSessionID",
        "WeekendInfo.EventType",
        "WeekendInfo.Category",
        "WeekendInfo.SimMode",
        "WeekendInfo.WeekendOptions.NumStarters",
        "WeekendInfo.WeekendOptions.Date",
        "WeekendInfo.WeekendOptions.TimeOfDay",
        "DriverInfo.DriverCarIdx",
        "DriverInfo.DriverUserID",
        "DriverInfo.DriverSetupName",
        "DriverInfo.DriverCarRedLine",
        "DriverInfo.DriverCarFuelMaxLtr",
        "DriverInfo.DriverCarSLFirstRPM",
        "DriverInfo.DriverCarSLShiftRPM",
        "DriverInfo.DriverCarSLLastRPM",
        "DriverInfo.DriverCarSLBlinkRPM",
        "SessionInfo.CurrentSessionNum",
        "SessionInfo.Sessions[0].SessionType",
        "SessionInfo.Sessions[0].SessionName",
        "SessionInfo.Sessions[0].SessionLaps",
        "SessionInfo.Sessions[0].SessionTime",
        "SessionInfo.Sessions[0].ResultsNumCautionFlags",
        "SessionInfo.Sessions[0].ResultsNumCautionLaps"
    ];

    private static readonly Dictionary<string, string> PreviewValues = new(StringComparer.OrdinalIgnoreCase)
    {
        ["WeekendInfo.TrackName"] = "okayama_short",
        ["WeekendInfo.TrackDisplayName"] = "Mock Track",
        ["WeekendInfo.TrackDisplayShortName"] = "Mock",
        ["WeekendInfo.TrackConfigName"] = "Grand Prix",
        ["WeekendInfo.TrackType"] = "Road",
        ["WeekendInfo.TrackDirection"] = "clockwise",
        ["WeekendInfo.TrackWeatherType"] = "Constant",
        ["WeekendInfo.TrackSkies"] = "Partly Cloudy",
        ["WeekendInfo.TrackAirTemp"] = "24 C",
        ["WeekendInfo.TrackSurfaceTemp"] = "31 C",
        ["WeekendInfo.TrackWindVel"] = "6 kph",
        ["WeekendInfo.TrackWindDir"] = "NE",
        ["WeekendInfo.SeriesID"] = "0",
        ["WeekendInfo.SeasonID"] = "0",
        ["WeekendInfo.SessionID"] = "0",
        ["WeekendInfo.SubSessionID"] = "0",
        ["WeekendInfo.EventType"] = "Race",
        ["WeekendInfo.Category"] = "Road",
        ["WeekendInfo.SimMode"] = "full",
        ["WeekendInfo.WeekendOptions.NumStarters"] = "24",
        ["WeekendInfo.WeekendOptions.Date"] = "2026-04-13",
        ["WeekendInfo.WeekendOptions.TimeOfDay"] = "13:30",
        ["DriverInfo.DriverCarIdx"] = "0",
        ["DriverInfo.DriverUserID"] = "1",
        ["DriverInfo.DriverSetupName"] = "Baseline",
        ["DriverInfo.DriverCarRedLine"] = "9000",
        ["DriverInfo.DriverCarFuelMaxLtr"] = "100",
        ["DriverInfo.DriverCarSLFirstRPM"] = "7000",
        ["DriverInfo.DriverCarSLShiftRPM"] = "7800",
        ["DriverInfo.DriverCarSLLastRPM"] = "8200",
        ["DriverInfo.DriverCarSLBlinkRPM"] = "8500",
        ["SessionInfo.CurrentSessionNum"] = "0",
        ["SessionInfo.Sessions[0].SessionType"] = "Race",
        ["SessionInfo.Sessions[0].SessionName"] = "Race",
        ["SessionInfo.Sessions[0].SessionLaps"] = "20",
        ["SessionInfo.Sessions[0].SessionTime"] = "1800 sec",
        ["SessionInfo.Sessions[0].ResultsNumCautionFlags"] = "0",
        ["SessionInfo.Sessions[0].ResultsNumCautionLaps"] = "0",
        ["Speed"] = "123",
        ["Gear"] = "4",
        ["RPM"] = "7420",
        ["ShiftIndicatorPct"] = "0.82",
        ["Throttle"] = "0.76",
        ["Brake"] = "0.00",
        ["Clutch"] = "0.00",
        ["SteeringWheelAngle"] = "-18.2",
        ["SteeringWheelPctTorque"] = "0.11",
        ["Lap"] = "12",
        ["LapCompleted"] = "11",
        ["LapCurrentLapTime"] = "84.253",
        ["LapLastLapTime"] = "84.112",
        ["LapBestLapTime"] = "83.901",
        ["LapDistPct"] = "0.48",
        ["LapDeltaToBestLap"] = "+0.352",
        ["LapDeltaToSessionBestLap"] = "+0.487",
        ["SessionLapsRemain"] = "8",
        ["SessionTimeRemain"] = "652.3",
        ["SessionFlags"] = "0",
        ["PlayerCarPosition"] = "6",
        ["PlayerCarClassPosition"] = "2",
        ["CarIdxPosition[0]"] = "6",
        ["CarIdxClassPosition[0]"] = "2",
        ["FuelLevel"] = "42.5",
        ["FuelLevelPct"] = "0.53",
        ["FuelUsePerHour"] = "2.91",
        ["OilTemp"] = "103.4",
        ["WaterTemp"] = "96.8",
        ["Voltage"] = "13.7",
        ["OnPitRoad"] = "False",
        ["PitSvFlags"] = "0",
        ["PitSvFuel"] = "0.0",
        ["SpeedLimiter"] = "False",
        ["IsOnTrack"] = "True",
        ["IsInGarage"] = "False",
        ["IsReplayPlaying"] = "False",
        ["Yaw"] = "0.04",
        ["Pitch"] = "-0.01",
        ["Roll"] = "0.02",
        ["VelocityX"] = "0.0",
        ["VelocityY"] = "34.1",
        ["VelocityZ"] = "0.0",
        ["LatAccel"] = "1.62",
        ["LongAccel"] = "-0.08",
        ["VertAccel"] = "0.01"
    };

    public static IReadOnlyList<string> GetFields(string source)
        => string.Equals(source, "SessionInfo", StringComparison.OrdinalIgnoreCase)
            ? SessionInfoFields
            : TelemetryFields;

    public static string GetPreviewValue(string source, string fieldPath)
    {
        if (string.IsNullOrWhiteSpace(fieldPath))
        {
            return string.Empty;
        }

        return PreviewValues.TryGetValue(fieldPath, out var preview)
            ? preview
            : fieldPath;
    }
}
